/**
 * Export Service - Generate downloadable outputs
 *
 * Creates:
 * - LaTeX source (.tex)
 * - Markdown (.md)
 * - Overleaf-ready ZIP (main.tex + figures/)
 * - PDF (via external compilation service)
 */

import JSZip from "jszip";
import { renderToLatex, validateLatex, type LaTeXOptions } from "./latex-renderer";
import { renderToMarkdown, type MarkdownOptions } from "./markdown-renderer";
import type { DocumentJSON } from "./types";

export interface ExportOptions {
  format: "latex" | "markdown" | "overleaf" | "pdf" | "all";
  title?: string;
  author?: string;
  includeSource?: boolean;
}

export interface ExportResult {
  latex?: string;
  markdown?: string;
  overleafZip?: Blob;
  pdf?: Blob;
  errors?: string[];
}

/**
 * Export a document to various formats
 */
export async function exportDocument(
  document: DocumentJSON,
  figures: Map<string, Blob>, // imagePath -> Blob
  options: ExportOptions
): Promise<ExportResult> {
  const result: ExportResult = {};
  const errors: string[] = [];

  const latexOptions: LaTeXOptions = {
    title: options.title,
    author: options.author,
  };

  const markdownOptions: MarkdownOptions = {
    title: options.title,
    includeYamlFrontmatter: true,
  };

  // Generate LaTeX
  if (
    options.format === "latex" ||
    options.format === "overleaf" ||
    options.format === "pdf" ||
    options.format === "all"
  ) {
    result.latex = renderToLatex(document, latexOptions);

    // Validate
    const validation = validateLatex(result.latex);
    if (!validation.valid) {
      errors.push(...validation.errors.map((e) => `LaTeX: ${e}`));
    }
  }

  // Generate Markdown
  if (options.format === "markdown" || options.format === "all") {
    result.markdown = renderToMarkdown(document, markdownOptions);
  }

  // Generate Overleaf ZIP
  if (options.format === "overleaf" || options.format === "all") {
    try {
      result.overleafZip = await createOverleafZip(
        result.latex!,
        figures,
        options
      );
    } catch (error) {
      errors.push(
        `ZIP creation failed: ${error instanceof Error ? error.message : "Unknown"}`
      );
    }
  }

  if (errors.length > 0) {
    result.errors = errors;
  }

  return result;
}

/**
 * Create Overleaf-ready ZIP package
 */
async function createOverleafZip(
  latex: string,
  figures: Map<string, Blob>,
  options: ExportOptions
): Promise<Blob> {
  const zip = new JSZip();

  // Add main.tex
  zip.file("main.tex", latex);

  // Add figures folder
  const figuresFolder = zip.folder("figures");
  if (figuresFolder) {
    for (const [path, blob] of figures.entries()) {
      const filename = path.split("/").pop() || "figure.png";
      figuresFolder.file(filename, blob);
    }
  }

  // Add .latexmkrc for build configuration
  zip.file(
    ".latexmkrc",
    `$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error %O %S';
$pdf_mode = 1;
$bibtex_use = 0;`
  );

  // Add README
  zip.file(
    "README.md",
    `# ${options.title || "Document"}

Generated by type-it-up

## Compilation

### Overleaf
1. Upload this ZIP to Overleaf
2. Click "Compile"

### Local
\`\`\`bash
pdflatex main.tex
\`\`\`

## Contents
- main.tex - Main document
- figures/ - Extracted figures
`
  );

  return zip.generateAsync({ type: "blob" });
}

/**
 * Generate LaTeX source file content
 */
export function generateLatexSource(
  document: DocumentJSON,
  options: LaTeXOptions = {}
): string {
  return renderToLatex(document, options);
}

/**
 * Generate Markdown source file content
 */
export function generateMarkdownSource(
  document: DocumentJSON,
  options: MarkdownOptions = {}
): string {
  return renderToMarkdown(document, options);
}
